### ISSUE TITLE
Locations Not Showing in Beneficiary Database - High (Web Ess Issue)

### ISSUE THREAD

**Issue by Happs80** [humansis/api#10]
@Happs80 This issue is caused from the API, should be move it to https://github.com/humansis/api/issues?

We need to run the command php bin/console doctrine:fixtures:load --append --group=location via the deployment to re-import the location files at https://github.com/humansis/api/tree/dev/src/CommonBundle/DataFixtures/LocationFiles

**Comment by Happs80** [comment]
humansis/api#9

**Comment by chivy-we** [comment]
It is fixed. Please have a look at https://demo.humansis.org/

**Comment by Happs80** [comment]
Yes. Saw that. Thanks!
